spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/community2
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        #서비스 제공자에 대한 정보
        #redirect할 로그인페이지가 어디인지
        #access 토큰을 발급 받는 url 이 어딘지
        #access 토큰을 제공하여 사용자 정보를 회수할 url 은 어디인지
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        #서비스 제공자를 사용하기 위한 정보
        #클라이언트를 식별하기 위한 정보
        registration:
          naver:
            client-id: 3SaTcPJnVTQW_UEQxyVI
            client-secret: qZRVAKZNxi
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - nickname
              - email
              - profile_image
jwt:
  secret: jqwpoeijqopgmsawmeporiawmepoawpijrpoweiajafa08w74bufyieanfuiyeurgq78iY786